spring:
  datasource:
    url: ${DB_URL}
    username: shubhambhayana
    password: Sanshu105*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
